sudo: false
language: cpp

env:
  global:
    - LLVM_VERSION=3.8.0
    # Maintenance note: to move to a new version
    # of boost, update both BOOST_ROOT and BOOST_URL.
    # Note that for simplicity, BOOST_ROOT's final
    # namepart must match the folder name internal
    # to boost's .tar.gz.
    - LCOV_ROOT=$HOME/lcov
    - GDB_ROOT=$HOME/gdb
    - LCOV_EXCLUDE_FILES="*/src/test/*"
    - BOOST_ROOT=$HOME/boost_1_67_0
    - BOOST_URL='http://sourceforge.net/projects/boost/files/boost/1.67.0/boost_1_67_0.tar.gz'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-5.0
    packages:
      - gcc-5
      - g++-5
      - python-software-properties
      - protobuf-compiler
      - libprotobuf-dev
      - libssl-dev
      - libstdc++6
      - binutils-gold
      - gdb
      - texinfo
      - cmake
      - lcov
      - llvm-5.0
      - clang-5.0

matrix:
  include:

    - compiler: gcc
      env:
      - GCC_VER=5
      - BUILD_TYPE=Debug
      - TARGET=coverage
      - CMAKE_EXTRA_ARGS=-Dcoverage=ON
      - APP=ripple-offline-tool
      - APP_ARGS=--unittest

    - compiler: clang
      env:
      - GCC_VER=5
      - BUILD_TYPE=Debug
      - APP=ripple-offline-tool
      - APP_ARGS=--unittest
      cache:
        directories:
          - $GDB_ROOT

    - compiler: gcc
      env:
      - GCC_VER=5
      - BUILD_TYPE=Release
      - APP=ripple-offline-tool
      - APP_ARGS=--unittest

    - compiler: clang
      env:
      - GCC_VER=5
      - BUILD_TYPE=Release
      - APP=ripple-offline-tool
      - APP_ARGS=--unittest

cache:
  directories:
  - $BOOST_ROOT
  - $GDB_ROOT

before_install:
  - ( cd extras/rippled && bin/ci/ubuntu/install-dependencies.sh ../.. )

script:
  - extras/rippled/bin/ci/ubuntu/build-and-test.sh

notifications:
  email:
    false
  irc:
    channels:
      - "chat.freenode.net#ripple-dev"

